"""Add Group Info to Candidate

Revision ID: 4c505fc87ab2
Revises: c5339ffb1dd5
Create Date: 2020-05-25 14:21:07.564635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c505fc87ab2'
down_revision = 'c5339ffb1dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidate', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.drop_column('candidate', 'group_id')
    # ### end Alembic commands ###
