"""Add Pic Info to Candidate

Revision ID: badfacd7e53b
Revises: 4c505fc87ab2
Create Date: 2020-05-25 14:34:49.261890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badfacd7e53b'
down_revision = '4c505fc87ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('profile', sa.String(length=40), nullable=True))
    op.create_foreign_key(None, 'candidate', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.drop_column('candidate', 'profile')
    # ### end Alembic commands ###
